spring:
  datasource:
    hikari:
      connection-timeout: 10000
    url: ${datasource}?createDatabaseIfNotExist = true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    header: Authorization
    secret: ${jwt_secret}
    token-validity-in-seconds : 3600
    refresh-secret: ${jwt_secret_refresh}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

logging:
  file:
    name: /home/ubuntu/logs/foregg.log
  logback:
    rollingpolicy:
      file-name-pattern: /home/ubuntu/logs/foregg.%d{yyyy-MM-dd}-%i.log
      max-file-size: 8MB
      max-history: 14
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  level:
    root: INFO


fcm:
  key:
    path: foregg-56830-firebase-adminsdk-tgmbx-739218a1a0.json

server:
  port: 8080